name: Build Linux SGX SDK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_sdk:
    if: github.repository == 'initc3/nix-linux-sgx'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install nix from cachix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A sdk
  build_ipp:
    if: github.repository == 'initc3/nix-linux-sgx'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install nix from cachix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A ipp
  build_ae:
    if: github.repository == 'initc3/nix-linux-sgx'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install nix from cachix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A ae
